import '@/app/globals.css';
import '@ant-design/v5-patch-for-react-19';
import { NextIntlClientProvider } from 'next-intl';
import { AntdConfigProvider } from '@/shared/config/antd';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by REST Client app',
  icons: '/sun-svgrepo-com.svg',
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AntdRegistry>
      <NextIntlClientProvider>
        <AntdConfigProvider>{children}</AntdConfigProvider>
      </NextIntlClientProvider>
    </AntdRegistry>
  );
}
