import '@/app/globals.css';
import '@ant-design/v5-patch-for-react-19';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { AntdConfigProvider } from '@/shared/config/antd';
import { Header, Footer } from '@/widgets';
import type { Metadata } from 'next';
import { LanguageSelectProps } from '@/i18n/model/types';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by REST Client app',
  icons: '/sun-svgrepo-com.svg',
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<LanguageSelectProps>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <AntdConfigProvider>
            <Header locale={locale} />
            <main>{children}</main>
            <Footer />
          </AntdConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
